ld = { log:display $args } ;
lde = { log:exception-display $args } ;
la = { bundle:list -t 0 $args } ;
ls = { service:list $args } ;
cl = { config:list "(service.pid=$args)" } ;
halt = { system:shutdown -h -f $args } ;
help = { *:help $args | more } ;
man = { help $args } ;
log:list = { log:get ALL } ;
service:get = { $.context getService ($.context getServiceReference $args) };

env = { shell:set $args }
edit = { shell:nano $args }
more = { shell:less -F $args }

__load_class = {
  (($.reader class) classLoader) loadClass $1
}

// make sure that we catch exceptions
// as they do occur if the session is headless / non-interactive
jlineReader = $.reader
if { %(jlineReader != null) } {


  setopt group
  setopt auto-fresh-line
  unsetopt insert-tab
  keymap "^[OA" up-line-or-search
  keymap "^[[A" up-line-or-search
  keymap "^[OB" down-line-or-search
  keymap "^[[B" down-line-or-search
}
 console set
 //logtail -c
 //mhus:log settrail

